//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WumpusHunt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WumpusHunt.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your arrow goes hurtling down the corridor. You hear it hit the cave floor.
        /// </summary>
        internal static string ArrowMiss {
            get {
                return ResourceManager.GetString("ArrowMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the action to take.
        /// </summary>
        internal static string EnterAction {
            get {
                return ResourceManager.GetString("EnterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hear growling.
        /// </summary>
        internal static string Growling {
            get {
                return ResourceManager.GetString("Growling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bump into a wall.
        /// </summary>
        internal static string HitWall {
            get {
                return ResourceManager.GetString("HitWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You hear a scream as the arrow strikes the wumpus, killing it.
        /// </summary>
        internal static string KillWumpus {
            get {
                return ResourceManager.GetString("KillWumpus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no arrows to fire.
        /// </summary>
        internal static string NoArrows {
            get {
                return ResourceManager.GetString("NoArrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing happened.
        /// </summary>
        internal static string NothingHappened {
            get {
                return ResourceManager.GetString("NothingHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wumpus sees you and charges, gobbling you up before you have a chance to run away.
        /// </summary>
        internal static string WumpusDeath {
            get {
                return ResourceManager.GetString("WumpusDeath", resourceCulture);
            }
        }
    }
}
